version: '3.8'

services:
  # Backend - CV Agent API
  cv-agent-api:
    build: .
    container_name: cv-agent-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - cv-agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - React App
  cv-agent-frontend:
    build: ./cv-agent-front
    container_name: cv-agent-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - cv-agent-api
    networks:
      - cv-agent-network
    restart: unless-stopped

networks:
  cv-agent-network:
    driver: bridge

volumes:
  cv_data:
    driver: local